// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	ID          int64
	Source      string
	Destination string
}

type User struct {
	ID          int64
	FirstName   string
	LastName    string
	Email       string
	Passhash    string
	Salt        string
	PhoneNumber pgtype.Text
}
